export type Severity = 'Low' | 'Medium' | 'High';
export type IncidentStatus = 'Resolved' | 'In Progress' | 'Unresolved';

export interface Incident {
  ir_id: number;
  date: string;
  issue: string;
  assignee: string;
  severity: Severity;
  project: string;
  developer: string;
  project_marketer: string;
  state: 'NSW' | 'VIC' | 'QLD';
  category: string;
  process_and_fix: string;
  notes: string;
  contact: string;
  status: IncidentStatus;
}

export const CATEGORIES = [
  'Hardware/Display',
  'Hardware/NUC',
  'Hardware/Audio',
  'Hardware/Remote',
  'Chrome',
  'Internet',
  'Lighting',
  'Showcase/Backend',
  'Showcase/Assets',
  'Showcase/Builder',
  'On-Site Electrical',
  'Miscellaneous',
  'User Error',
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    ir_id: 1,
    date: '2025-05-08',
    issue: 'Corner LED panels not turning on after power cycle',
    assignee: 'Jordan',
    severity: 'High',
    project: 'Hume Place',
    developer: 'Third I',
    project_marketer: '',
    state: 'NSW',
    category: 'Hardware/Display',
    process_and_fix: 'Walked the agent through the Kramer control panel to power cycle the LED wall. Confirmed all panels online after restart. Identified a loose power connector on panel 3 — flagged for on-site visit.',
    notes: 'Second occurrence this month. Scheduling Boston for a site inspection next week.',
    contact: 'Aimee',
    status: 'Resolved',
  },
  {
    ir_id: 2,
    date: '2025-05-10',
    issue: 'Showcase app stuck on loading screen — suite unusable during client meeting',
    assignee: 'Boston',
    severity: 'High',
    project: 'Moonee Valley',
    developer: '',
    project_marketer: '',
    state: 'VIC',
    category: 'Chrome',
    process_and_fix: 'Hard refreshed Chrome kiosk remotely via NUC remote access. App recovered within 2 minutes. Root cause appears to be a stale session token — session management fix flagged to product team.',
    notes: 'Client was present during the outage. Agent handled it well.',
    contact: 'Giulianna',
    status: 'Resolved',
  },
  {
    ir_id: 3,
    date: '2025-05-12',
    issue: 'Audio crackling from apartment zone speakers — intermittent',
    assignee: 'Jordan',
    severity: 'Medium',
    project: 'Brunswick Quarter',
    developer: 'Pace Development Group',
    project_marketer: 'CBRE',
    state: 'VIC',
    category: 'Hardware/Audio',
    process_and_fix: 'Power cycled the LEA Professional AMP remotely — issue persisted. Escalated to Aria for on-site callout. Aria confirmed faulty output channel on the audio processor and replaced it.',
    notes: 'Aria callout completed 20/05. Invoice to follow.',
    contact: 'Marcello',
    status: 'Resolved',
  },
  {
    ir_id: 4,
    date: '2025-05-14',
    issue: 'NUC offline — no screenshot in dashboard for 4+ hours during business hours',
    assignee: 'Jordan',
    severity: 'Medium',
    project: 'The Daintree Residences',
    developer: 'Mirvac',
    project_marketer: '',
    state: 'NSW',
    category: 'Hardware/NUC',
    process_and_fix: 'Attempted remote restart — no response. Contacted on-site agent to physically restart the NUC. NUC came back online after power cycle. Internet connection had dropped at router level.',
    notes: '',
    contact: 'Carlos',
    status: 'Resolved',
  },
  {
    ir_id: 5,
    date: '2025-05-15',
    issue: 'Kramer tablet showing incorrect URL — controls not responding',
    assignee: 'Boston',
    severity: 'Low',
    project: 'Hume Place',
    developer: 'Third I',
    project_marketer: '',
    state: 'NSW',
    category: 'Hardware/Remote',
    process_and_fix: 'Guided agent through re-entering the correct Kramer URL on the tablet. Credentials retrieved from the internal password manager. All controls confirmed working after update.',
    notes: '',
    contact: 'Aimee',
    status: 'Resolved',
  },
  {
    ir_id: 6,
    date: '2025-05-17',
    issue: 'Project switching broken — suite loading wrong development after selection',
    assignee: 'Boston',
    severity: 'High',
    project: 'Walden',
    developer: 'Aland',
    project_marketer: 'SRM',
    state: 'NSW',
    category: 'Showcase/Backend',
    process_and_fix: 'Reproduced the issue in staging — stale session key in Showcase Builder was referencing a deleted project. Removed the key and re-registered the session. Deployed fix to production. Verified all projects loading correctly.',
    notes: 'Also impacted a secondary suite at Motiv Brisbane — same fix applied.',
    contact: 'Eileen',
    status: 'Resolved',
  },
  {
    ir_id: 7,
    date: '2025-05-19',
    issue: 'Lighting script not responding to Kramer triggers after suite update',
    assignee: 'Jordan',
    severity: 'Low',
    project: 'Hume Place',
    developer: 'Third I',
    project_marketer: '',
    state: 'NSW',
    category: 'Lighting',
    process_and_fix: 'Ended and restarted the lighting script on the server. Re-tested all Kramer trigger zones — all zones responding correctly. Suspect the update process killed the script process without restarting it.',
    notes: 'Added script auto-restart to the deployment checklist.',
    contact: 'Aimee',
    status: 'Resolved',
  },
  {
    ir_id: 8,
    date: '2025-05-21',
    issue: 'Internet outage affecting entire display suite — NUC and all tablets offline',
    assignee: 'Jordan',
    severity: 'Medium',
    project: 'Newstead Green',
    developer: 'Consolidated Properties',
    project_marketer: '',
    state: 'QLD',
    category: 'Internet',
    process_and_fix: 'Confirmed outage via NUC dashboard — no screenshots since 9:00am. Contacted agent on-site. ISP had scheduled maintenance not communicated to client. Suite back online at 2:45pm once ISP maintenance completed.',
    notes: '',
    contact: 'Ben',
    status: 'Resolved',
  },
  {
    ir_id: 9,
    date: '2025-05-23',
    issue: 'Surface tablet stuck on Windows login screen — agent cannot access Showcase',
    assignee: 'Boston',
    severity: 'Low',
    project: 'River Quarter',
    developer: 'Lendlease',
    project_marketer: '',
    state: 'QLD',
    category: 'Hardware/Remote',
    process_and_fix: 'Remoted in via TeamViewer. Auto sign-in registry key had been cleared by a Windows update. Re-entered credentials in the registry editor and restarted the device. Showcase launched correctly on reboot.',
    notes: '',
    contact: 'Jess',
    status: 'Resolved',
  },
  {
    ir_id: 10,
    date: '2025-05-24',
    issue: 'Display showing "No Signal" on main presentation screen after TV replacement',
    assignee: 'Jordan',
    severity: 'Medium',
    project: 'Elmwood Park',
    developer: 'Stockland',
    project_marketer: '',
    state: 'NSW',
    category: 'Hardware/Display',
    process_and_fix: 'New TV defaulted to wrong HDMI input source. Walked agent through changing the input via TV remote. Confirmed display back on correct source. Also updated the input source label on the NUC HDMI output for clarity.',
    notes: 'TV replacement was not communicated to Tech Ops in advance — flagged to Sales team.',
    contact: 'Sarah',
    status: 'In Progress',
  },
];
